/**
 * Drizzle schema.
 *
 * The four tables below (`user`, `session`, `account`, `verification`) are the
 * Better Auth model. Better Auth validates this shape on every query and 500s
 * at runtime if any required column is missing, so they ship pre-defined and
 * correct — do NOT trim "unused" columns (the OAuth token fields on `account`,
 * `ipAddress`/`userAgent` on `session`) even for email+password-only apps.
 *
 * App-specific tables: add them BELOW the Better Auth block during the
 * schema-translation task (translate db_schema.reference.json into Drizzle
 * code here). Keep the Better Auth tables intact.
 */

import {
  boolean,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

// ---------------------------------------------------------------------------
// Better Auth tables — required shape. Do not modify column names/types.
// ---------------------------------------------------------------------------

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("created_at", { withTimezone: false }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: false }).notNull().defaultNow(),
});

export const session = pgTable("session", {
  id: text("id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  token: text("token").notNull().unique(),
  expiresAt: timestamp("expires_at", { withTimezone: false }).notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  createdAt: timestamp("created_at", { withTimezone: false }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: false }).notNull().defaultNow(),
});

export const account = pgTable("account", {
  id: text("id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: false }),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: false }),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at", { withTimezone: false }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: false }).notNull().defaultNow(),
});

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: false }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: false }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: false }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// App tables — ThreadHunter domain tables.
// ---------------------------------------------------------------------------

/** Allowed plan values for a workspace. */
export type WorkspacePlan = "free" | "starter" | "pro";

/** A founder's product workspace: one product → one workspace, multiple subreddits. */
export const workspaces = pgTable("workspaces", {
  id: text("id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  /** ICP (Ideal Customer Profile): plain-language description of who buys this product. */
  description: text("description").notNull(),
  productUrl: text("product_url").notNull().default(""),
  subreddits: text("subreddits").array().notNull().default([]),
  /** Semantic queries generated by OpenAI from the product description and ICP. */
  expandedQueries: text("expanded_queries").array().notNull().default([]),
  /** Keywords/phrases a thread must match to be included (empty = no filter). */
  allowRules: text("allow_rules").array().notNull().default([]),
  /** Keywords/phrases that disqualify a thread from scoring. */
  blockRules: text("block_rules").array().notNull().default([]),
  /** Billing plan for this workspace. Defaults to free tier. */
  plan: text("plan").$type<WorkspacePlan>().notNull().default("free"),
  /** Stripe customer ID associated with this workspace's owner. */
  stripeCustomerId: text("stripe_customer_id"),
  /** Active Stripe subscription ID for this workspace. */
  stripeSubscriptionId: text("stripe_subscription_id"),
  createdAt: timestamp("created_at", { withTimezone: false }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: false }).notNull().defaultNow(),
});

/** Intent label values allowed for a detected Reddit thread. */
export type IntentLabel =
  | "asking-for-recs"
  | "complaining-about-incumbent"
  | "comparing-tools"
  | "unrelated";

/**
 * A Reddit thread discovered for a workspace, deduplicated by
 * (workspaceId, redditPostId). Unique index ensures the same post is
 * only stored once per workspace even if re-crawled.
 */
export const threads = pgTable(
  "threads",
  {
    id: text("id").primaryKey(),
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    redditPostId: text("reddit_post_id").notNull(),
    redditUrl: text("reddit_url").notNull(),
    title: text("title").notNull(),
    body: text("body").notNull().default(""),
    subreddit: text("subreddit").notNull(),
    intentLabel: text("intent_label")
      .$type<IntentLabel>()
      .notNull()
      .default("unrelated"),
    intentScore: integer("intent_score").notNull().default(0),
    suggestedAngle: text("suggested_angle"),
    replyScaffold: text("reply_scaffold"),
    falsePositive: boolean("false_positive").notNull().default(false),
    /** Set when this thread appears in a weekly digest email. */
    digestSentAt: timestamp("digest_sent_at", { withTimezone: false }),
    createdAt: timestamp("created_at", { withTimezone: false }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: false }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("threads_workspace_post_idx").on(t.workspaceId, t.redditPostId)],
);

/** Status values for a digest run. */
export type DigestRunStatus = "pending" | "running" | "completed" | "failed";

/** A scheduled or on-demand weekly digest execution for a workspace. */
export const digestRuns = pgTable("digest_runs", {
  id: text("id").primaryKey(),
  workspaceId: text("workspace_id")
    .notNull()
    .references(() => workspaces.id, { onDelete: "cascade" }),
  status: text("status")
    .$type<DigestRunStatus>()
    .notNull()
    .default("pending"),
  ranAt: timestamp("ran_at", { withTimezone: false }),
  createdAt: timestamp("created_at", { withTimezone: false }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: false }).notNull().defaultNow(),
});

/** Ranked threads included in a digest run (5–10 per run, ordered by rank). */
export const digestRunThreads = pgTable("digest_run_threads", {
  id: text("id").primaryKey(),
  digestRunId: text("digest_run_id")
    .notNull()
    .references(() => digestRuns.id, { onDelete: "cascade" }),
  threadId: text("thread_id")
    .notNull()
    .references(() => threads.id, { onDelete: "cascade" }),
  rank: integer("rank").notNull(),
  createdAt: timestamp("created_at", { withTimezone: false }).notNull().defaultNow(),
});
